Repository sygmaprotocol/sygma-widget, pull requests merged in 2024-04, with the labels that each got.

#144 feat: Transfer UI page
  examples/react-widget-app/src/App.css
  examples/react-widget-app/src/App.tsx
  examples/react-widget-app/src/public/closeIcon.png
  examples/react-widget-app/src/public/docsIcon.png
  examples/react-widget-app/src/public/githubIcon.png
  examples/react-widget-app/src/public/sidebarIcon.png
  examples/react-widget-app/src/public/sygmaIcon.svg
Labels: Priority: P1

#149 chore: Merge main into dev
  .github/CODEOWNERS
  .github/workflows/cf-deploy-react.yml
  .github/workflows/cf-deploy-widget.yml
  examples/react-widget-app/src/App.css
  examples/react-widget-app/src/App.tsx
  examples/react-widget-app/src/public/closeIcon.png
  examples/react-widget-app/src/public/docsIcon.png
  examples/react-widget-app/src/public/githubIcon.png
  examples/react-widget-app/src/public/sidebarIcon.png
  examples/react-widget-app/src/public/sygmaIcon.svg
  packages/widget/.env.development
  packages/widget/.env.production
  packages/widget/package.json
  packages/widget/src/components/address-input/address-input.ts
  packages/widget/src/components/amount-selector/index.ts
  packages/widget/src/components/common/buttons/connect-wallet.ts
  packages/widget/src/components/common/dropdown/dropdown.ts
  packages/widget/src/components/index.ts
  packages/widget/src/components/network-selector/network-selector.ts
  packages/widget/src/components/resource-amount-selector/index.ts
  packages/widget/src/components/resource-amount-selector/resource-amount-selector.ts
  packages/widget/src/components/resource-amount-selector/styles.ts
  packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts
  packages/widget/src/components/transfer/fungible/transfer-detail/transfer-detail.ts
  packages/widget/src/components/transfer/fungible/transfer-status/transfer-status.ts
  packages/widget/src/context/config.ts
  packages/widget/src/context/index.ts
  packages/widget/src/context/wallet.ts
  packages/widget/src/controllers/transfers/evm/build.ts
  packages/widget/src/controllers/transfers/fungible-token-transfer.ts
  packages/widget/src/controllers/wallet-manager/manager.ts
  packages/widget/src/controllers/wallet-manager/token-balance.ts
  packages/widget/src/interfaces/index.ts
  packages/widget/src/utils/token.ts
  packages/widget/src/vite-env.d.ts
  packages/widget/src/widget.ts
  packages/widget/tests/unit/components/address-input/address-input.test.ts
  packages/widget/tests/unit/components/amount-selector/amount-selector.test.ts
  packages/widget/tests/unit/components/resource-amount-selector/resource-amount-selector.test.ts
  packages/widget/tests/unit/components/transfer-detail/transfer-detail.test.ts
  packages/widget/tests/unit/components/transfer/fungible/fungible-token-transfer.test.ts
  packages/widget/tests/unit/context/config.test.ts
  packages/widget/tests/unit/controllers/transfers/fungible-token-transfer.test.ts
  packages/widget/tests/unit/setup.ts
  packages/widget/vite.config.ts
Labels: Priority: P1

#176 fix: bug where user could proceed with invalid destination address
  packages/widget/src/components/address-input/address-input.ts
  packages/widget/src/components/transfer/fungible/transfer-button/transfer-button.ts
  packages/widget/src/controllers/transfers/fungible-token-transfer.ts
  packages/widget/tests/unit/components/transfer/fungible/fungible-token-transfer.test.ts
Labels: QA

#60 chore: release main
  .release-please-manifest.json
  packages/react/CHANGELOG.md
  packages/widget/CHANGELOG.md
Labels: autorelease: pending, QA

#179 chore: release main
  .release-please-manifest.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/widget/CHANGELOG.md
  packages/widget/package.json
Labels: autorelease: pending

#180 chore: release main
  .release-please-manifest.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/widget/CHANGELOG.md
  packages/widget/package.json
Labels: autorelease: pending
